Cliffd/file refactor
SenteraLLC/py-6x-corrections pull request #5
Opened 2020-10-22 14:56 UTC by cliff-dellamano

# `py-6x-corrections` Initial Release

## What?
Looks like it's time, folks. This PR is a full refactor of the library, so there's a lot to go through here. Big ticket items:
* The helper functions that were originally grouped together with the `correct_6x_images` scripts have been separated out
into modules that make more sense according to their use. Also, most of the actual business logic was refactored into functions as well.
* Reflectance calibration via calibration panels has been integrated into the script (thanks to @dzermas)
* Many use-cases requiring the parsing of EXIF/XMP metadata have been added to `py-image-metadata-parser` as first-class citizens.

## Why?
* This will mark the first "release" of the library that is suitable for public use. There are still things that can be done to improve
the user experience (`click` CLI bindings) as well as better practices from a developer standpoint (test suite, documentation, etc.), but these can be done post-release. 

## PR Checklist
- [x] Merged latest master
- [x] Updated version number
- [x] All private git packages are at their newest version in *environment.yml*

2020-10-22 15:27 UTC, dzermas requested changes
LGTM. Just consider changing the name of the `convert_to_type` function.

2020-10-22 15:27 UTC, dzermas commented on correct6x/detect_panel.py
> +def convert_to_type(image, desired_type=np.uint8):
This should probably be called ` convert_12bit_to_type`

2020-10-23 17:14 UTC, ZachMarston approved these changes
LGTM, pending Dimitris' requested change.

2020-10-23 18:26 UTC, dzermas approved these changes
LGTM

2020-10-23 18:37 UTC, merged